# Generated by Django 6.0.3 on 2026-04-05 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TrafficCamera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Tên Camera")),
                (
                    "image_source_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="URL Ảnh trực tiếp"
                    ),
                ),
                (
                    "last_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="live_snapshots/"
                    ),
                ),
                ("current_density", models.FloatField(default=0.0)),
                ("current_vehicle_count", models.IntegerField(default=0)),
                (
                    "current_traffic_level",
                    models.CharField(default="Thông thoáng", max_length=50),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TrafficHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("density_pce", models.FloatField()),
                ("vehicle_count", models.IntegerField()),
                ("traffic_level", models.CharField(max_length=50)),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="analytics.trafficcamera",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
