# Generated by Django 6.0.3 on 2026-04-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trafficcamera",
            name="camera_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="ID Camera (Hex)",
            ),
        ),
    ]
