# Generated by Django 6.0.3 on 2026-04-06 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_trafficcamera_camera_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="trafficcamera",
            name="latitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Vĩ độ"),
        ),
        migrations.AddField(
            model_name="trafficcamera",
            name="longitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Kinh độ"),
        ),
    ]
