# Generated by Django 6.0.3 on 2026-04-06 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0003_trafficcamera_latitude_trafficcamera_longitude"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemoResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_file", models.FileField(upload_to="demo_uploads/")),
                (
                    "processed_video",
                    models.FileField(blank=True, null=True, upload_to="demo_results/"),
                ),
                ("mode", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("analytics_json", models.TextField(blank=True, null=True)),
                ("total_vehicles", models.IntegerField(default=0)),
                ("peak_density", models.FloatField(default=0.0)),
            ],
        ),
    ]
