# Generated by Django 6.0.3 on 2026-04-06 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0004_demoresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="trafficcamera",
            name="road_area_pixels",
            field=models.IntegerField(
                default=15000, verbose_name="Diện tích lòng đường (px)"
            ),
        ),
    ]
